---
# This playbook loops over the provided roles, installs them and runs tasks
- hosts: all
  gather_facts: false
  tasks:
    # This is less "agressive" then setting variables directly from the "-e" option
    - name: Set global facts
      set_fact: {"{{ item.key }}": "{{ item.value }}"}
      with_dict: "{{ global_vars | default({}) }}"

    # Loop over all provided roles and run tasks
    - name: Run lifecycle roles
      include_tasks: lifecycle_role.yml
      with_items:
        - "{{ lifecycle_roles if (lifecycle_order | default('normal')) != 'reverse' else (lifecycle_roles | reverse | list) }}"
      when:
        - (lifecycle_actions | list | length) > 0
      loop_control:
        loop_var: role
