---
- hosts: all
  gather_facts: false
  tasks:
    # This is less "agressive" then setting variables directly from the "-e" option
    - name: Set global facts
      set_fact: {"{{ item.key }}": "{{ item.value }}"}
      with_dict: "{{ global_vars | default({}) }}"

    # Loop over all provided roles and run tasks
    - name: Setup, Provision, Deprovision Roles
      include_tasks: provisioner_role.yml
      with_flattened:
        # Reverses order when deprovisioning
        - "{{ provisioning_roles if provisioner=='create' else [] }}"
        - "{{ (provisioning_roles | reverse | list) if provisioner=='destroy' else [] }}"
      loop_control:
        loop_var: role
