---
- hosts: all
  gather_facts: false
  tasks:
    # This is less "agressive" then setting variables directly from the "-e" option
    - name: Set global facts
      set_fact: {"{{ item.key }}": "{{ item.value }}"}
      with_dict: "{{ global_vars | default({}) }}"

    # Loop over all provided roles and run tasks
    - name: Setup, Provision, Deprovision Roles
      include_tasks: provisioning_role.yml
      with_items:
        - "{{ provisioning_roles if (provisioning_order | default('normal')) != 'reverse' else (provisioning_roles | reverse | list) }}"
      when:
        - (provisioning_actions | list | length) > 0
      loop_control:
        loop_var: role
